name: 部署选股器

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Pages
        uses: actions/configure-pages@v4

      - name: 上传Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: 部署到Pages
        id: deployment
        uses: actions/deploy-pages@v4
